In [1]:
import numpy as np

In [2]:
WIDTH = 25
HEIGHT = 6

In [3]:
with open('day8-input.txt') as in_file:
    data = [int(s) for s in in_file.read()]
    
layers = np.array(data).reshape(-1, WIDTH * HEIGHT)

In [4]:
zeroes_count = np.inf
min_count = None

for i in layers:
    _, counts = np.unique(i, return_counts=True)
    
    if counts[0] < zeroes_count:
        zeroes_count = counts[0]
        min_count = counts
        print(counts)

[ 14  12 124]
[  9   9 132]
[  8  10 132]


In [5]:
# part 1
min_count[1] * min_count[2]

1320

In [6]:
flayers = layers[::-1]
res = flayers[0]

for i in flayers:
    i[i == 2] = res[i == 2]
    res = i

In [7]:
# part 2
for a in res.reshape(HEIGHT, WIDTH):
    ss = ['#' if i else ' ' for i in a]
    print(''.join(ss))

###   ##  #   ##  # ###  
#  # #  # #   ## #  #  # 
#  # #     # # ##   #  # 
###  #      #  # #  ###  
# #  #  #   #  # #  # #  
#  #  ##    #  #  # #  # 
